// SPDX-License-Identifier: AGPL-3.0-or-later
package org.pingme.core.connector

import org.pingme.core.model.AccountId
import org.pingme.core.model.AttachmentId
import org.pingme.core.model.ChatId
import org.pingme.core.model.MessageId
import org.pingme.core.model.PersonId
import org.pingme.core.model.SpaceId

// PingMe IDs for things that live on a network are "<account id>/<network's own id>".
// Two accounts on the same network never collide, and any ID says which account it is
// for. Account IDs are generated by PingMe and never contain '/'; the network's part may.

private const val SEPARATOR = '/'

private fun scoped(
    account: AccountId,
    remote: String,
): String {
    require(SEPARATOR !in account.value) { "Account IDs never contain '$SEPARATOR'" }
    return "${account.value}$SEPARATOR$remote"
}

private fun accountPart(id: String) = AccountId(id.substringBefore(SEPARATOR))

private fun remotePart(id: String) = id.substringAfter(SEPARATOR)

fun AccountId.chat(remoteId: String) = ChatId(scoped(this, remoteId))

fun AccountId.message(remoteId: String) = MessageId(scoped(this, remoteId))

fun AccountId.attachment(remoteId: String) = AttachmentId(scoped(this, remoteId))

fun AccountId.person(remoteId: String) = PersonId(scoped(this, remoteId))

fun AccountId.space(remoteId: String) = SpaceId(scoped(this, remoteId))

val ChatId.accountId get() = accountPart(value)
val ChatId.remoteId get() = remotePart(value)
val MessageId.accountId get() = accountPart(value)
val MessageId.remoteId get() = remotePart(value)
val AttachmentId.accountId get() = accountPart(value)
val AttachmentId.remoteId get() = remotePart(value)
val PersonId.accountId get() = accountPart(value)
val PersonId.remoteId get() = remotePart(value)
val SpaceId.accountId get() = accountPart(value)
val SpaceId.remoteId get() = remotePart(value)
